name: Crosspost

on:
  repository_dispatch:
    types: [crosspost]

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Echo message
        env:
          TWEET_TEXT: ${{ github.event.client_payload.tweetText }}
          TWEET_CREATED_AT: ${{ github.event.client_payload.tweetCreatedAt }}
          TWEET_URL: ${{ github.event.client_payload.tweetUrl }}
        run: echo $TWEET_TEXT

      - name: Execute crosspost
        env:
          TWEET_TEXT: ${{ github.event.client_payload.tweetText }}
          TWEET_CREATED_AT: ${{ github.event.client_payload.tweetCreatedAt }}
          TWEET_URL: ${{ github.event.client_payload.tweetUrl }}
        run: npm start -w crosspost
